# Generated by Django 3.2.15 on 2023-01-07 09:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_auto_20230105_1629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourite',
            new_name='Favorite',
        ),
        migrations.RenameModel(
            old_name='ShoppingCart',
            new_name='ShoppingList',
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Favorite', 'verbose_name_plural': 'Favorites'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#000000', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid HEX color.', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='HEX color'),
        ),
    ]
